version: "3.9"

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: music
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
