version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: music
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"